# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'g:\Python\PasswordMaker_SourceCode\MainWindow.ui'
#
# Created by: PyQt5 UI code generator 5.14.2
#
# WARNING! All changes made in this file will be lost!


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(800, 600)
        font = QtGui.QFont()
        font.setPointSize(9)
        MainWindow.setFont(font)
        MainWindow.setStyleSheet("")
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.editWeb = QtWidgets.QLineEdit(self.centralwidget)
        self.editWeb.setGeometry(QtCore.QRect(50, 90, 700, 50))
        font = QtGui.QFont()
        font.setFamily("Microsoft YaHei")
        font.setPointSize(12)
        self.editWeb.setFont(font)
        self.editWeb.setAlignment(QtCore.Qt.AlignLeading|QtCore.Qt.AlignLeft|QtCore.Qt.AlignVCenter)
        self.editWeb.setPlaceholderText("")
        self.editWeb.setObjectName("editWeb")
        self.makePassword = QtWidgets.QPushButton(self.centralwidget)
        self.makePassword.setGeometry(QtCore.QRect(50, 260, 700, 50))
        font = QtGui.QFont()
        font.setFamily("Microsoft YaHei")
        font.setPointSize(12)
        self.makePassword.setFont(font)
        self.makePassword.setObjectName("makePassword")
        self.label = QtWidgets.QLabel(self.centralwidget)
        self.label.setGeometry(QtCore.QRect(50, 330, 700, 50))
        font = QtGui.QFont()
        font.setFamily("Microsoft YaHei")
        font.setPointSize(12)
        self.label.setFont(font)
        self.label.setObjectName("label")
        self.showPassword = QtWidgets.QLineEdit(self.centralwidget)
        self.showPassword.setGeometry(QtCore.QRect(50, 400, 590, 50))
        font = QtGui.QFont()
        font.setFamily("Microsoft YaHei")
        font.setPointSize(12)
        self.showPassword.setFont(font)
        self.showPassword.setText("")
        self.showPassword.setEchoMode(QtWidgets.QLineEdit.Password)
        self.showPassword.setAlignment(QtCore.Qt.AlignLeading|QtCore.Qt.AlignLeft|QtCore.Qt.AlignVCenter)
        self.showPassword.setReadOnly(True)
        self.showPassword.setPlaceholderText("")
        self.showPassword.setObjectName("showPassword")
        self.label_2 = QtWidgets.QLabel(self.centralwidget)
        self.label_2.setGeometry(QtCore.QRect(50, 30, 700, 50))
        font = QtGui.QFont()
        font.setFamily("Microsoft YaHei")
        font.setPointSize(12)
        self.label_2.setFont(font)
        self.label_2.setObjectName("label_2")
        self.changeFormula = QtWidgets.QPushButton(self.centralwidget)
        self.changeFormula.setGeometry(QtCore.QRect(50, 480, 330, 50))
        font = QtGui.QFont()
        font.setFamily("Microsoft YaHei")
        font.setPointSize(12)
        self.changeFormula.setFont(font)
        self.changeFormula.setStyleSheet("")
        self.changeFormula.setObjectName("changeFormula")
        self.hasUL = QtWidgets.QCheckBox(self.centralwidget)
        self.hasUL.setGeometry(QtCore.QRect(50, 160, 185, 30))
        font = QtGui.QFont()
        font.setFamily("Microsoft YaHei")
        font.setPointSize(12)
        self.hasUL.setFont(font)
        self.hasUL.setChecked(True)
        self.hasUL.setObjectName("hasUL")
        self.hasNumber = QtWidgets.QCheckBox(self.centralwidget)
        self.hasNumber.setGeometry(QtCore.QRect(420, 160, 175, 30))
        font = QtGui.QFont()
        font.setFamily("Microsoft YaHei")
        font.setPointSize(12)
        self.hasNumber.setFont(font)
        self.hasNumber.setObjectName("hasNumber")
        self.hasLL = QtWidgets.QCheckBox(self.centralwidget)
        self.hasLL.setGeometry(QtCore.QRect(235, 160, 185, 30))
        font = QtGui.QFont()
        font.setFamily("Microsoft YaHei")
        font.setPointSize(12)
        self.hasLL.setFont(font)
        self.hasLL.setChecked(True)
        self.hasLL.setObjectName("hasLL")
        self.hasSymbol = QtWidgets.QCheckBox(self.centralwidget)
        self.hasSymbol.setGeometry(QtCore.QRect(595, 160, 155, 30))
        font = QtGui.QFont()
        font.setFamily("Microsoft YaHei")
        font.setPointSize(12)
        self.hasSymbol.setFont(font)
        self.hasSymbol.setObjectName("hasSymbol")
        self.chooseComplexity = QtWidgets.QSlider(self.centralwidget)
        self.chooseComplexity.setGeometry(QtCore.QRect(188, 210, 560, 30))
        font = QtGui.QFont()
        font.setFamily("Microsoft YaHei")
        font.setPointSize(12)
        self.chooseComplexity.setFont(font)
        self.chooseComplexity.setMinimum(3)
        self.chooseComplexity.setMaximum(10)
        self.chooseComplexity.setOrientation(QtCore.Qt.Horizontal)
        self.chooseComplexity.setObjectName("chooseComplexity")
        self.label_3 = QtWidgets.QLabel(self.centralwidget)
        self.label_3.setGeometry(QtCore.QRect(50, 210, 130, 30))
        font = QtGui.QFont()
        font.setFamily("Microsoft YaHei")
        font.setPointSize(12)
        self.label_3.setFont(font)
        self.label_3.setIndent(0)
        self.label_3.setObjectName("label_3")
        self.copy = QtWidgets.QPushButton(self.centralwidget)
        self.copy.setGeometry(QtCore.QRect(660, 400, 90, 50))
        font = QtGui.QFont()
        font.setFamily("Microsoft YaHei")
        font.setPointSize(12)
        self.copy.setFont(font)
        self.copy.setObjectName("copy")
        self.importFormula = QtWidgets.QPushButton(self.centralwidget)
        self.importFormula.setGeometry(QtCore.QRect(420, 480, 330, 50))
        font = QtGui.QFont()
        font.setFamily("Microsoft YaHei")
        font.setPointSize(12)
        self.importFormula.setFont(font)
        self.importFormula.setStyleSheet("")
        self.importFormula.setObjectName("importFormula")
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 800, 18))
        self.menubar.setObjectName("menubar")
        self.menulang = QtWidgets.QMenu(self.menubar)
        self.menulang.setObjectName("menulang")
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)
        self.zh_cn = QtWidgets.QAction(MainWindow)
        self.zh_cn.setObjectName("zh_cn")
        self.en = QtWidgets.QAction(MainWindow)
        self.en.setObjectName("en")
        self.menulang.addAction(self.zh_cn)
        self.menulang.addAction(self.en)
        self.menubar.addAction(self.menulang.menuAction())

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "Password Maker"))
        self.makePassword.setText(_translate("MainWindow", "Make Password"))
        self.label.setText(_translate("MainWindow", "Password:"))
        self.label_2.setText(_translate("MainWindow", "Website:"))
        self.changeFormula.setText(_translate("MainWindow", "Change formula"))
        self.hasUL.setText(_translate("MainWindow", "Upper letters"))
        self.hasNumber.setText(_translate("MainWindow", "Numbers"))
        self.hasLL.setText(_translate("MainWindow", "Lower letters"))
        self.hasSymbol.setText(_translate("MainWindow", "Symbols"))
        self.label_3.setText(_translate("MainWindow", "Complexity:"))
        self.copy.setText(_translate("MainWindow", "Copy"))
        self.importFormula.setText(_translate("MainWindow", "Import formula"))
        self.menulang.setTitle(_translate("MainWindow", "languages"))
        self.zh_cn.setText(_translate("MainWindow", "中文（简体）"))
        self.en.setText(_translate("MainWindow", "English"))
